[package]
name = "bf_bot_compiler"
version = "0.1.0"
authors = ["Arjan Boschman <a.boschman@hotmail.com>"]
workspace="../brain_fuck_joust"

[dependencies]

[dependencies.bf_bot_core]
path = "../bf_bot_core"